shell.program = "zsh"

[window.padding]
x = 10
y = 10

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Medium"

[font.bold]
family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.italic]
family = "MonaspiceNe Nerd Font"
style = "Medium Italic"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

# Gruvbox Material Dark Medium
[colors.normal]
black = "0x665c54"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a4e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[colors.bright]
black = "0x928374"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe3a84e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"
